### ISSUE TITLE
Code must run on gpus?

### ISSUE THREAD

**Issue by usherbob** [tinyalpha/BPR#12]
I tried to run released code on CPUs, however, there's an error.

```
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
  File "./tools/test_float.py", line 148, in <module>
    main()
  File "./tools/test_float.py", line 101, in main
    init_dist(args.launcher, **cfg.dist_params)
  File "/home/mi/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 20, in init_dist
    _init_dist_pytorch(backend, **kwargs)
  File "/home/mi/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 33, in _init_dist_pytorch
    torch.cuda.set_device(rank % num_gpus)
ZeroDivisionError: integer division or modulo by zero
Traceback (most recent call last):
  File "./tools/test_float.py", line 148, in <module>
    main()
  File "./tools/test_float.py", line 101, in main
    init_dist(args.launcher, **cfg.dist_params)
  File "/home/mi/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 20, in init_dist
    _init_dist_pytorch(backend, **kwargs)
  File "/home/mi/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 33, in _init_dist_pytorch
    torch.cuda.set_device(rank % num_gpus)
ZeroDivisionError: integer division or modulo by zero
Traceback (most recent call last):
  File "./tools/test_float.py", line 148, in <module>
Traceback (most recent call last):
  File "./tools/test_float.py", line 148, in <module>
    main()
  File "./tools/test_float.py", line 101, in main
    main()
  File "./tools/test_float.py", line 101, in main
    init_dist(args.launcher, **cfg.dist_params)
  File "/home/mi/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 20, in init_dist
    init_dist(args.launcher, **cfg.dist_params)
  File "/home/mi/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 20, in init_dist
    _init_dist_pytorch(backend, **kwargs)
  File "/home/mi/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 33, in _init_dist_pytorch
    _init_dist_pytorch(backend, **kwargs)
  File "/home/mi/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/dist_utils.py", line 33, in _init_dist_pytorch
    torch.cuda.set_device(rank % num_gpus)
ZeroDivisionError: integer division or modulo by zero
    torch.cuda.set_device(rank % num_gpus)
ZeroDivisionError: integer division or modulo by zero
Traceback (most recent call last):
  File "/home/mi/miniconda3/envs/open-mmlab/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/mi/miniconda3/envs/open-mmlab/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/mi/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/home/mi/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 257, in main
    cmd=cmd)
```

**Comment by chenhang98** [comment]
Sorry, our codes only support GPU inference.

**Comment by pbebbo** [comment]
Would running the BPR algorithm on a CPU cause a bottleneck?
