### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'mask_rcnn_101/coarse_train_filtered.json'

### ISSUE THREAD

**Issue by Lopside1** [tinyalpha/BPR#29]
**Checklist**

**1. I have searched related issues but cannot get the expected help.**
I have googled the issue, tried searching on this repo and mmsegmentation

**2. The bug has not been fixed in the latest version.**
Fresh pull today

**Describe the bug**
Hi I hope someone can help me understand what needs to be done to get this to work a little better. Below is the full details but essentially my issue is converting from a coco data format from Mask RCNN: the script is expecting a "coarse_train_filtered.json" file and I am not sure what this is or why it is missing/not generated.

I am trying to convert output data from Mask RCNN output  (which has been converted into the coco format) and I have created the following files from the back of it:
```mask_rcnn_101.train.segm.json```
```mask_rcnn_101.val.segm.json```

and a data structure:
```
BPR
├── data
│   ├── coco
│   │   ├── annotations
│   │   ├── train2017
│   │   ├── val2017
│   │   ├── test2017
```
as per the coco standard and the documentation here. When I try to convert the coco dataset with prepare_dataset_coco.sh I am getting the following error.

```FileNotFoundError: [Errno 2] No such file or directory: 'mask_rcnn_101/coarse_train_filtered.json'```

I am unsure of what this file is and what it should be doing. Please could you assist with my understanding. 

**Reproduction**

**1. What command or script did you run?**
```none
IOU_THRESH=0.15 \
sh tools/prepare_dataset_coco.sh \
mask_rcnn_101.train.segm.json \
mask_rcnn_101.val.segm.json \
mask_rcnn_101
10000
```

**2. Did you make any modifications on the code or config? Did you understand what you have modified?**
None that I am aware of - I am using my own dataset but tried to fully respect the expected format

**3. What dataset did you use?**
Personal one formatted like coco with the above structure

**Environment**

1. Please run `python mmseg/utils/collect_env.py` to collect necessary environment information and paste it here.
```
sys.platform: linux
Python: 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:21) [GCC 9.4.0]
CUDA available: True
GPU 0: Tesla K80
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.3, V11.3.109
GCC: gcc (Debian 8.3.0-6) 8.3.0
PyTorch: 1.10.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.11.1
OpenCV: 4.5.5
MMCV: 1.5.0
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.3
MMSegmentation: 0.24.1+a615828
```
**2. You may add addition that may be helpful for locating the problem, such as**
    - How you installed PyTorch [e.g., pip, **conda**, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)
 ```
    - LD_LIBRARY_PATH=/usr/local/cuda/lib64:/usr/local/nccl2/lib:/usr/local/cuda/extras/CUPTI/lib64
    - PATH=/usr/local/cuda/bin:/opt/conda/envs/open-mmlab/bin:/opt/conda/condabin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
```
**Error traceback**

**OUTPUT FROM ABOVE COMMAND**
```
build training set ...
+ python ./tools/filter.py mask_rcnn_101.train.segm.json data/coco/annotations/instances_train2017.json mask_rcnn_101/coarse_train_filtered.json
loading annotations into memory...
Done (t=0.03s)
creating index...
index created!
Traceback (most recent call last):
  File "./tools/filter.py", line 65, in <module>
    Fire(main)
  File "/opt/conda/envs/open-mmlab/lib/python3.7/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/conda/envs/open-mmlab/lib/python3.7/site-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/opt/conda/envs/open-mmlab/lib/python3.7/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "./tools/filter.py", line 58, in main
    dt = json.load(open(dt_json))
  File "/opt/conda/envs/open-mmlab/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/opt/conda/envs/open-mmlab/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/opt/conda/envs/open-mmlab/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/conda/envs/open-mmlab/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
+ python ./tools/split_patches.py mask_rcnn_101/coarse_train_filtered.json data/coco/annotations/instances_train2017.json data/coco/train2017 mask_rcnn_101/patches --iou-thresh 0.15 --mode train --sample-inst 10000
mkdir: cannot create directory ‘mask_rcnn_101/patches/img_dir’: File exists
mkdir: cannot create directory ‘mask_rcnn_101/patches/ann_dir’: File exists
mkdir: cannot create directory ‘mask_rcnn_101/patches/mask_dir’: File exists
mkdir: cannot create directory ‘mask_rcnn_101/patches/detail_dir’: File exists
mkdir: cannot create directory ‘mask_rcnn_101/patches/img_dir/train’: File exists
mkdir: cannot create directory ‘mask_rcnn_101/patches/ann_dir/train’: File exists
mkdir: cannot create directory ‘mask_rcnn_101/patches/mask_dir/train’: File exists
mkdir: cannot create directory ‘mask_rcnn_101/patches/detail_dir/train’: File exists
loading annotations into memory...
Done (t=0.03s)
creating index...
index created!
Traceback (most recent call last):
  File "./tools/split_patches.py", line 291, in <module>
    start()
  File "./tools/split_patches.py", line 239, in start
    dt = json.load(open(args.dt_json))
FileNotFoundError: [Errno 2] No such file or directory: 'mask_rcnn_101/coarse_train_filtered.json'
+ printf \033[0;32mbuild validation set ...\033[0m\n
```

**Bug fix**

If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by chenhang98** [comment]
Hi, according to your terminal output (`dt = json.load(open(dt_json))`), the error occurs when loading mask_rcnn_101.train.segm.json.
You can check whether this file is in the correct format and can be loaded with `json.load`.

**Comment by Lopside1** [comment]
> Hi, according to your terminal output (`dt = json.load(open(dt_json))`), the error occurs when loading mask_rcnn_101.train.segm.json. You can check whether this file is in the correct format and can be loaded with `json.load`.

Hi, thank you for your rapid response. Yes, I have found my data wasn't in the correct format as you suggest, easy to miss a key value! Thank you, this is a great repo thank you very much for sharing!
